/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Visual;

/**
 *
 * @author paulo
 */
public class Alerts extends javax.swing.JFrame {

    /**
     * Creates new form Alerts
     */
    public Alerts() {

        initComponents();
        titleSubTitle.setText(Visual.getSubsidiary().getDisplayName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        titleAlert = new javax.swing.JLabel();
        titleSubTitle = new javax.swing.JLabel();
        btnLockdown = new javax.swing.JButton();
        bntChangeSistem = new javax.swing.JButton();
        btnDistanceAlert = new javax.swing.JButton();
        bntgInfectedAlert = new javax.swing.JButton();
        bntVaccinatedAlert = new javax.swing.JButton();
        bntCleanAlert = new javax.swing.JButton();
        backAlert = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleAlert.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        titleAlert.setText("Quadros de Alertas");

        titleSubTitle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        titleSubTitle.setText("Subisidiaria");

        btnLockdown.setText("LOCKDOWN ");
        btnLockdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLockdownActionPerformed(evt);
            }
        });

        bntChangeSistem.setText("SISTEMAS DE RODIZIO");
        bntChangeSistem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntChangeSistemActionPerformed(evt);
            }
        });

        btnDistanceAlert.setText("AVISO DE  DISTANCIAMENTO");
        btnDistanceAlert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDistanceAlertActionPerformed(evt);
            }
        });

        bntgInfectedAlert.setText("AVISO DE INFECTADOS");
        bntgInfectedAlert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntgInfectedAlertActionPerformed(evt);
            }
        });

        bntVaccinatedAlert.setText("AVISO DE VACINADOS");
        bntVaccinatedAlert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntVaccinatedAlertActionPerformed(evt);
            }
        });

        bntCleanAlert.setText("AVISO DE LIMPEZA");
        bntCleanAlert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCleanAlertActionPerformed(evt);
            }
        });

        backAlert.setText("Voltar");
        backAlert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backAlertActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(270, 270, 270)
                                                .addComponent(titleAlert))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(310, 310, 310)
                                                .addComponent(titleSubTitle))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(30, 30, 30)
                                                .addComponent(btnLockdown, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(30, 30, 30)
                                                .addComponent(bntChangeSistem, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(40, 40, 40)
                                                .addComponent(btnDistanceAlert, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(30, 30, 30)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(backAlert)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(bntgInfectedAlert, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(30, 30, 30)
                                                                .addComponent(bntVaccinatedAlert, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(40, 40, 40)
                                                                .addComponent(bntCleanAlert, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(titleAlert)
                                .addGap(8, 8, 8)
                                .addComponent(titleSubTitle)
                                .addGap(113, 113, 113)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnLockdown, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(bntChangeSistem, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnDistanceAlert, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(bntgInfectedAlert, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(bntVaccinatedAlert, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(bntCleanAlert, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                                .addComponent(backAlert)
                                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>

    private void btnDistanceAlertActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void btnLockdownActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void backAlertActionPerformed(java.awt.event.ActionEvent evt) {
        setVisible(false);
        dispose();
        Home.execute();
    }

    private void bntgInfectedAlertActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void bntChangeSistemActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void bntVaccinatedAlertActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void bntCleanAlertActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Alerts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Alerts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Alerts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Alerts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Alerts().setVisible(true);
            }
        });
    }

    public static void execute() {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Alerts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton backAlert;
    private javax.swing.JButton bntChangeSistem;
    private javax.swing.JButton bntCleanAlert;
    private javax.swing.JButton bntVaccinatedAlert;
    private javax.swing.JButton bntgInfectedAlert;
    private javax.swing.JButton btnDistanceAlert;
    private javax.swing.JButton btnLockdown;
    private javax.swing.JLabel titleAlert;
    private javax.swing.JLabel titleSubTitle;
    // End of variables declaration
}
