/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Visual;
import Model.Employee;
import Model.Subsidiary;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;

/**
 *
 * @author paulo
 */
public class EmployeeManager extends javax.swing.JFrame {

    /**
     * Creates new form EmplyeeManager
     */
    public EmployeeManager() {

        initComponents();
        titleSubEmployeeManager.setText(Visual.getSubsidiary().getDisplayName());
        Visual.getSubsidiary().print();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        Object [][] defaultData = new Object [][] {
        };

        Object [] defaultColumn = new String [] {
                "Nome", "Cargo", "Setor", "Infectado", "Vacinado", "Regime de Trabalho"
        };

        tableModel = new DefaultTableModel(defaultData, defaultColumn);
        for (Employee employee: Visual.getSubsidiary().getEmployees()) {
            String isInfected = "Não";
            String isImmunized = "Não";
            if(employee.isInfected()) {
                isInfected = "Sim";
            }
            if(employee.isImmunized()) {
                isImmunized = "Sim";
            }
            tableModel.addRow(new Object[]{employee.getFullName(), employee.getRole(), employee.getLocation(), isInfected, isImmunized, employee.getWorkMethod()});
        }
        titleEmployeeManager = new javax.swing.JLabel();
        titleSubEmployeeManager = new javax.swing.JLabel();
        tblEmployeeManager = new JTable(tableModel);
        jScrollPane1 = new javax.swing.JScrollPane();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        btnBackEmployeeManager = new javax.swing.JButton();
        btnAddEmployee = new javax.swing.JButton();
        btnDeleteEmployee = new javax.swing.JButton();
        btnEditEmployee = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleEmployeeManager.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        titleEmployeeManager.setText("Gerenciar Funcionários");

        titleSubEmployeeManager.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        titleSubEmployeeManager.setText("Subsidiary");

        jScrollPane1.setViewportView(tblEmployeeManager);

        btnBackEmployeeManager.setText("< Voltar");
        btnBackEmployeeManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackEmployeeManagerActionPerformed(evt);
            }
        });

        btnAddEmployee.setText("Adicionar Funcionário");
        btnAddEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEmployeeActionPerformed(evt);
            }
        });

        btnDeleteEmployee.setText("Remover Funcionário");
        btnDeleteEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteEmployeeActionPerformed(evt);
            }
        });

        btnEditEmployee.setText("Salvar Modificações");
        btnEditEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditEmployeeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(70, 70, 70)
                                                .addComponent(jScrollPane1)
                                                .addGap(45, 45, 45)
                                                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(btnBackEmployeeManager, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(314, 314, 314)
                                                .addComponent(btnAddEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnDeleteEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnEditEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(18, 18, 18))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(350, 350, 350)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addComponent(titleEmployeeManager)
                                        .addComponent(titleSubEmployeeManager))
                                .addGap(340, 340, 340))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(258, 258, 258)
                                                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(114, 114, 114)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                                        .addComponent(btnDeleteEmployee)
                                                        .addComponent(btnEditEmployee)
                                                        .addComponent(btnBackEmployeeManager)
                                                        .addComponent(btnAddEmployee)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(28, 28, 28)
                                                .addComponent(titleEmployeeManager, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(titleSubEmployeeManager, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(45, 45, 45)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(90, 90, 90)))
                                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>

    private void btnBackEmployeeManagerActionPerformed(java.awt.event.ActionEvent evt) {
        setVisible(false);
        dispose();
        Home.execute();
    }

    private void btnDeleteEmployeeActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            tableModel.removeRow(tblEmployeeManager.getSelectedRow());
        } catch (Exception e) {
            System.out.println("É necessário selecionar a linha que você deseja remover!");
        }
    }

    private void btnAddEmployeeActionPerformed(java.awt.event.ActionEvent evt) {
        tableModel.addRow(new Object[] {"", "", "", "", "", ""});
    }

    private void btnEditEmployeeActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            tblEmployeeManager.getCellEditor().stopCellEditing();
        } catch (Exception e) {}
        Subsidiary subsidiary = Visual.getSubsidiary();
        subsidiary.setEmployees(new ArrayList<>());
        for (int i = 0; i < tableModel.getRowCount(); i++) {
            boolean isInfected = false;
            boolean isImmunized = false;
            if(tableModel.getDataVector().get(i).get(3).equals("Sim") || tableModel.getDataVector().get(i).get(3).equals("sim") || tableModel.getDataVector().get(i).get(3).equals("S") || tableModel.getDataVector().get(i).get(3).equals("s")) {
                isInfected = true;
            }
            if(tableModel.getDataVector().get(i).get(4).equals("Sim") || tableModel.getDataVector().get(i).get(4).equals("sim") || tableModel.getDataVector().get(i).get(4).equals("S") || tableModel.getDataVector().get(i).get(4).equals("s")) {
                isImmunized = true;
            }
            subsidiary.addEmployee(new Employee(tableModel.getDataVector().get(i).get(0).toString(), tableModel.getDataVector().get(i).get(1).toString(), tableModel.getDataVector().get(i).get(2).toString(), isInfected, isImmunized, tableModel.getDataVector().get(i).get(5).toString()));
        }
        Visual.setSubsidiary(subsidiary);
        JOptionPane.showMessageDialog(null, "Modificação salva com sucesso!");
    }

    public static void execute() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeManager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton btnAddEmployee;
    private javax.swing.JButton btnBackEmployeeManager;
    private javax.swing.JButton btnDeleteEmployee;
    private javax.swing.JButton btnEditEmployee;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEmployeeManager;
    private javax.swing.JLabel titleEmployeeManager;
    private javax.swing.JLabel titleSubEmployeeManager;
    private DefaultTableModel tableModel;
    // End of variables declaration
}
