/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Visual;
import Model.Email;
import Model.Employee;

/**
 *
 * @author paulo
 */
public class WorkMethod extends javax.swing.JFrame {

    /**
     * Creates new form WorkMethod
     */
    public WorkMethod() {

        initComponents();
        titleSubWorkMethod.setText(Visual.getSubsidiary().getDisplayName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        titleWorkMethod = new javax.swing.JLabel();
        titleSubWorkMethod = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        backWorkMethod = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleWorkMethod.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        titleWorkMethod.setText("Gerencia Regime de Trabalho");

        titleSubWorkMethod.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        titleSubWorkMethod.setText("Subsidiary");

        jButton1.setText("Definir Todos");
        jButton1.setMaximumSize(new java.awt.Dimension(159, 23));
        jButton1.setMinimumSize(new java.awt.Dimension(159, 23));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Definir Hibrido/HomeOffice");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Definir HomeOffice");
        jButton3.setMaximumSize(new java.awt.Dimension(159, 23));
        jButton3.setMinimumSize(new java.awt.Dimension(159, 23));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        backWorkMethod.setText("< Voltar");
        backWorkMethod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backWorkMethodActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(342, 342, 342)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addComponent(titleWorkMethod)
                                        .addComponent(titleSubWorkMethod))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(backWorkMethod)
                                                .addGap(660, 660, 660))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(105, 105, 105))))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(titleWorkMethod)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(titleSubWorkMethod)
                                .addGap(158, 158, 158)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(203, 203, 203)
                                .addComponent(backWorkMethod)
                                .addGap(72, 72, 72))
        );

        pack();
    }// </editor-fold>

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        for (Employee employee: Visual.getSubsidiary().getEmployees()) {
            if(employee.getWorkMethod().equalsIgnoreCase("presencial")) {
                employee.setWorkMethod("Hibrido");

                if(employee.getEmails().size() > 0) {
                    for (Email email:employee.getEmails()) {
                        Visual.sendMail("Troca de Regime de Trabalho", "A partir de agora todos os funcionários deverão trabalhar apenas em Hibrido/HomeOffice.\n\nEssa medida é para a sua seguranda!",  email.getValue());
                    }
                }
            }
        }
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        for (Employee employee: Visual.getSubsidiary().getEmployees()) {
            if(employee.getEmails().size() > 0) {
                for (Email email:employee.getEmails()) {
                    Visual.sendMail("Troca de Regime de Trabalho", "A partir de agora todos os funcionários poderão voltar ao regime normal de trabalho.",  email.getValue());
                }
            }

        }
    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
        for (Employee employee: Visual.getSubsidiary().getEmployees()) {
            employee.setWorkMethod("HomeOffice");
            if(employee.getEmails().size() > 0) {
                for (Email email:employee.getEmails()) {
                    Visual.sendMail("Troca de Regime de Trabalho", "A partir de agora todos os funcionários deverão trabalhar apenas em HomeOffice.\n\nEssa medida é para a sua seguranda!",  email.getValue());
                }
            }
        }
    }

    private void backWorkMethodActionPerformed(java.awt.event.ActionEvent evt) {
        setVisible(false);
        dispose();
        Home.execute();
    }

    public static void execute() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WorkMethod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WorkMethod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WorkMethod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WorkMethod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WorkMethod().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton backWorkMethod;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel titleSubWorkMethod;
    private javax.swing.JLabel titleWorkMethod;
    // End of variables declaration
}
